## Authorizations
# Uncomment out the merging for each environment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# environment if you need something different per enviornment.

authorizations: &AUTHORIZATIONS
  group_base: ou=Groups,dc=lcseecloud,dc=net
  required_groups:
    - ["memberUid", "cn=sysstaff,ou=Group,dc=lcseecloud,dc=net"]	


## Environment

development:
  host: 
  port: 
  attribute: 
  base: 
#  admin_user: cn=admin,dc=test,dc=com
#  admin_password: admin_password
  ssl: false
  <<: *AUTHORIZATIONS

test:
  host: localhost
  port: 3389
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: simple_tls
  # <<: *AUTHORIZATIONS

production:
  host: 
  port: 
  attribute: 
  base: 
#  admin_user: 
#  admin_password: admin_password
  ssl: false
  <<: *AUTHORIZATIONS
